DATA:
  IMG_SIZE: 448 
MODEL:
  TYPE: swinv2
  NAME: swinv2_base_patch4_window24to28_384to448_1ktoMYDATA_ft
  
  DROP_PATH_RATE: 0.2
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 28 
    PRETRAINED_WINDOW_SIZES: [ 12, 12, 12, 6 ]
TRAIN:
  EPOCHS: 300 
  WARMUP_EPOCHS: 5
  # WEIGHT_DECAY: 1e-8
  # BASE_LR: 2e-05
  # WARMUP_LR: 2e-08
  # MIN_LR: 2e-07
TEST:
  CROP: False